ALTER TABLE post    ADD COLUMN hidden_by_withdrawal BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE comment ADD COLUMN hidden_by_withdrawal BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE message ADD COLUMN hidden_by_withdrawal BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE follow  ADD COLUMN hidden_by_withdrawal BOOLEAN NOT NULL DEFAULT FALSE;
